"""remove weather_api_key from fields

Revision ID: 0003
Revises: 0002
Create Date: 2025-01-13 02:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'weather_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('weather_api_key', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ### 