"""Add SKIPPED status to ScheduleStatus enum

Revision ID: 6165e6314722
Revises: b64c09fcbccd
Create Date: 2025-07-24 00:42:59.897300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6165e6314722'
down_revision = 'b64c09fcbccd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE schedulestatus ADD VALUE 'スキップ'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 