"""add hashed_password to user

Revision ID: 64da715a7b50
Revises: 0002
Create Date: 2025-07-11 08:01:08.746550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64da715a7b50'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ### 