"""fix user role enum mapping

Revision ID: 6b8571839b2c
Revises: 64da715a7b50
Create Date: 2025-07-11 09:30:32.474401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8571839b2c'
down_revision = '64da715a7b50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 