"""add_weather_cache_table

Revision ID: b64c09fcbccd
Revises: de44fbc43fcb
Create Date: 2025-07-16 23:44:22.963905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64c09fcbccd'
down_revision = 'de44fbc43fcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 