"""add_deleted_at_to_users

Revision ID: de44fbc43fcb
Revises: fe12cde55d40
Create Date: 2025-07-16 23:35:24.672879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de44fbc43fcb'
down_revision = 'fe12cde55d40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fields', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='畑名',
               existing_nullable=False)
    op.alter_column('fields', 'location_text',
               existing_type=sa.VARCHAR(length=255),
               comment='住所テキスト',
               existing_nullable=False)
    op.alter_column('fields', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='緯度',
               existing_nullable=True)
    op.alter_column('fields', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='経度',
               existing_nullable=True)
    op.alter_column('fields', 'image',
               existing_type=postgresql.BYTEA(),
               comment='畑の図面画像（バイナリ）',
               existing_nullable=True)
    op.alter_column('fields', 'created_by',
               existing_type=sa.INTEGER(),
               comment='作成者ID',
               existing_nullable=False)
    op.alter_column('fields', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='作成日時',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fields', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新日時',
               existing_nullable=True)
    op.alter_column('histories', 'schedule_id',
               existing_type=sa.INTEGER(),
               comment='スケジュールID',
               existing_nullable=False)
    op.alter_column('histories', 'user_id',
               existing_type=sa.INTEGER(),
               comment='実行ユーザーID',
               existing_nullable=False)
    op.alter_column('histories', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='実行日時',
               existing_nullable=False)
    op.alter_column('histories', 'status',
               existing_type=sa.VARCHAR(length=16),
               comment='実行状態',
               existing_nullable=False)
    op.alter_column('histories', 'comment',
               existing_type=sa.VARCHAR(length=300),
               comment='実行コメント',
               existing_nullable=True)
    op.alter_column('histories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='作成日時',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'field_id',
               existing_type=sa.INTEGER(),
               comment='畑ID',
               existing_nullable=False)
    op.alter_column('schedules', 'date',
               existing_type=sa.DATE(),
               comment='当番日',
               existing_nullable=False)
    op.alter_column('schedules', 'user_id',
               existing_type=sa.INTEGER(),
               comment='担当ユーザーID',
               existing_nullable=False)
    op.alter_column('schedules', 'status',
               existing_type=postgresql.ENUM('未実施', '完了', name='schedulestatus'),
               comment='スケジュール状態',
               existing_nullable=False)
    op.alter_column('schedules', 'comment',
               existing_type=sa.VARCHAR(length=500),
               comment='コメント',
               existing_nullable=True)
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='作成日時',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新日時',
               existing_nullable=True)
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='論理削除日時'))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='ユーザー名',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='メールアドレス',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='userrole'),
               comment='ユーザー権限',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='ハッシュ化されたパスワード',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='作成日時',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新日時',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新日時',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='ハッシュ化されたパスワード',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='userrole'),
               comment=None,
               existing_comment='ユーザー権限',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='メールアドレス',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='ユーザー名',
               existing_nullable=False)
    op.drop_column('users', 'deleted_at')
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新日時',
               existing_nullable=True)
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'comment',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='コメント',
               existing_nullable=True)
    op.alter_column('schedules', 'status',
               existing_type=postgresql.ENUM('未実施', '完了', name='schedulestatus'),
               comment=None,
               existing_comment='スケジュール状態',
               existing_nullable=False)
    op.alter_column('schedules', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='担当ユーザーID',
               existing_nullable=False)
    op.alter_column('schedules', 'date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='当番日',
               existing_nullable=False)
    op.alter_column('schedules', 'field_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='畑ID',
               existing_nullable=False)
    op.alter_column('histories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('histories', 'comment',
               existing_type=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='実行コメント',
               existing_nullable=True)
    op.alter_column('histories', 'status',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='実行状態',
               existing_nullable=False)
    op.alter_column('histories', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='実行日時',
               existing_nullable=False)
    op.alter_column('histories', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='実行ユーザーID',
               existing_nullable=False)
    op.alter_column('histories', 'schedule_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='スケジュールID',
               existing_nullable=False)
    op.alter_column('fields', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新日時',
               existing_nullable=True)
    op.alter_column('fields', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('fields', 'created_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='作成者ID',
               existing_nullable=False)
    op.alter_column('fields', 'image',
               existing_type=postgresql.BYTEA(),
               comment=None,
               existing_comment='畑の図面画像（バイナリ）',
               existing_nullable=True)
    op.alter_column('fields', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='経度',
               existing_nullable=True)
    op.alter_column('fields', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='緯度',
               existing_nullable=True)
    op.alter_column('fields', 'location_text',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='住所テキスト',
               existing_nullable=False)
    op.alter_column('fields', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='畑名',
               existing_nullable=False)
    # ### end Alembic commands ### 