"""add unique constraint field_id_date_user_id_to_schedules

Revision ID: f8c603f407ab
Revises: 6b8571839b2c
Create Date: 2025-07-11 11:10:30.349656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c603f407ab'
down_revision = '6b8571839b2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_field_date_user', 'schedules', ['field_id', 'date', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_field_date_user', 'schedules', type_='unique')
    # ### end Alembic commands ### 